# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Cloudbacon
name:                Cloudbacon
tagline:             'Building parts of the web'
description:         'Silent ramblings of a journeyman programmer, humorist, taskmaster, and  minitel core team member. Delicious responses plucked from the <a href="http://www.twitter.com/braidn">mind of braidn</a>'
url:                 http://cloudbacon.com
github:
  repo:             'https://github.com/braidn/Nesta-Cloudbacon-Blog'

# About/contact
author: Braden Douglass
author:
  name:              Braden Douglass
  url:               https://twitter.com/braidn
  email:             me at braidn dot com

# Custom vars
version:             1.1.5
gems:
  - jekyll-sitemap
