# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Cloudbacon
tagline:             'A flowy thought place'
description:         'Silent ramblings of a journeyman programmer, humorist, taskmaster, and  minitel core team member. Delicious responses plucked from the <a href="http://www.twitter.com/braidn">mind of braidn</a>'
url:                 http://cloudbacon.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Braden Douglass
  url:               https://twitter.com/braidn
  email:             me@braidn.com

# Custom vars
version:             1.0.0
gems:
  - jekyll-sitemap
